apiVersion: apps/v1
kind: Deployment
metadata:
  name: p5-movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: p5-movie
  template:
    metadata:
      labels:
        app: p5-movie
    spec:
      containers:
        - name: p5-movie-container
          image: bowenyang118/cs122b-p5-movie:v1 #your docker dir
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
      imagePullSecrets: # Specifies the secret to use for pulling the image (not needed for public images)
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: p5-movie-service
spec:
  selector:
    app: p5-movie
  ports:
    - name: http
      port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p5-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p5-login
  template:
    metadata:
      labels:
        app: p5-login
    spec:
      containers:
        - name: p5-login-container
          image: bowenyang118/cs122b-p5-login:v1 #your docker dir
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: p5-login-service
spec:
  selector:
    app: p5-login
  ports:
    - name: http
      port: 8080
  type: ClusterIP
